services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypass
      MONGO_DATABASE: tree_db
    ports:
      - '27017:27017'
    volumes:
      - ./.database/mongodb:/var/lib/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypass
      ME_CONFIG_MONGODB_URL: mongodb://myuser:mypass@db:27017/
      ME_CONFIG_BASICAUTH: false
